function RiskIntelligence({
  predictions = [],
  loading = false,
  error = "",
  onRelocation,
}) {
  const validPredictions = [...predictions]
    .filter(
      (item) =>
        item?.prediction &&
        typeof item.prediction.predictedScore === "number"
    )
    .sort(
      (a, b) =>
        b.prediction.predictedScore -
        a.prediction.predictedScore
    )
    .slice(0, 5);

  const getRiskClass = (risk) => {
    return `priority-badge risk-${String(
      risk || "LOW"
    ).toLowerCase()}`;
  };

  return (
    <section className="section intelligence-section">

      {/* ================= HEADER ================= */}

      <div className="section-heading">

        <div>

          <span className="section-kicker">
            DECISION SUPPORT ENGINE
          </span>

          <h2>
            🧠 Risk Intelligence
          </h2>

          <p>
            Backend-generated risk intelligence for
            emergency response planning.
          </p>

        </div>

        <div className="heading-icon">
          🧠
        </div>

      </div>

      {/* ================= INFO ================= */}

      <div className="intelligence-note">

        <span>ⓘ</span>

        <p>
          Risk predictions are generated by the
          SURAKSHA-X backend intelligence engine using
          hazard severity, affected population and
          hazard type.
        </p>

      </div>

      {/* ================= LOADING ================= */}

      {loading && (
        <div className="loading-state">

          <div className="loading-spinner"></div>

          <p>
            Generating risk intelligence...
          </p>

        </div>
      )}

      {/* ================= ERROR ================= */}

      {!loading && error && (
        <div className="form-error">
          ⚠️ {error}
        </div>
      )}

      {/* ================= EMPTY ================= */}

      {!loading &&
        !error &&
        validPredictions.length === 0 && (

          <div className="empty-state">

            <div>🧠</div>

            <h3>
              No Risk Signals
            </h3>

            <p>
              Add hazards to generate decision-support
              intelligence.
            </p>

          </div>
        )}

      {/* ================= PREDICTIONS ================= */}

      {!loading &&
        !error &&
        validPredictions.length > 0 && (

          <div className="intelligence-list">

            {validPredictions.map(
              (hazard, index) => {

                const prediction =
                  hazard.prediction;

                const risk =
                  prediction.predictedRisk ||
                  "LOW";

                return (
                  <div
                    className="intelligence-row"
                    key={hazard._id}
                  >

                    {/* RANK */}

                    <div className="intel-rank">
                      {index + 1}
                    </div>

                    {/* MAIN INFO */}

                    <div className="intel-main">

                      <strong>
                        {hazard.name ||
                          "Unknown Hazard"}
                      </strong>

                      <span>
                        {hazard.type ||
                          "Unknown Type"}{" "}
                        • Severity{" "}
                        {prediction.severity ?? 0}{" "}
                        •{" "}
                        {Number(
                          prediction.population ??
                            hazard.population ??
                            0
                        ).toLocaleString("en-IN")}{" "}
                        people
                      </span>

                    </div>

                    {/* SCORE */}

                    <div className="intel-score">

                      <strong>
                        {Number(
                          prediction.predictedScore
                        ).toFixed(0)}
                      </strong>

                      <span
                        className={getRiskClass(
                          risk
                        )}
                      >
                        {risk}
                      </span>

                    </div>

                    {/* RESPONSE */}

                    <button
                      type="button"
                      className="relocation-btn"
                      onClick={() =>
                        onRelocation?.(hazard)
                      }
                    >
                      Plan Response
                    </button>

                  </div>
                );
              }
            )}

          </div>
        )}

    </section>
  );
}

export default RiskIntelligence;
